### ISSUE TITLE
Remove all `Option<HashMap<K,V>>` in favor of  `HashMap<K,V>` with an empty default

### ISSUE THREAD

**Issue by LegNeato** [srijs/rust-aws-lambda#12]
It is more ergonomic to use an empty `HashMap` and set a default when serializing and deserializing instead of an `Option` so that code doesn't always have to check before using a field.

Because creating a default allocates, ideally we would put this behind a feature flag and let users decide if they prefer the ergonomics or (slight) perf increase.

**Comment by srijs** [comment]
IIRC creating an empty HashMap does not perform any heap allocations. Or are you referring to something else when you say ‚default‘?

**Comment by LegNeato** [comment]
Nope, I assumed it allocated but never checked. In that case I think this would strictly be a win.
