### ISSUE TITLE
Decide if Option<String> and Option<HashMap> should always respect features

### ISSUE THREAD

**Issue by LegNeato** [srijs/rust-aws-lambda#16]
Currently the `string-null-empty` feature only operates on fields that were not explicitly set as optional in the go sdk. If the field was set as optional, we don't generate an empty value for it and it stays an `Option<String>` on the Rust side. Similarly, we only synthesize empty `HashMap`s if the field was not explicitly set as optional.

This could be confusing, as sometimes you get a default and don't need to handle an `Option` (if the field was marked as required) and sometimes you do (if the field was marked as optional). One could reasonably expect to always get `String`s or `HashMap`s with a default and I am not sure the current distinction is clear or important.

Should we unify the behavior here to better match expectations? Or would users prefer the current split behavior that matches the go sdk?

**Comment by quezlatch** [comment]
that's a tricky one... I think go with the current behaviour, and see how things shake out after it's been used in the wild a bit

**Comment by LegNeato** [comment]
The events crate has now moved to https://github.com/LegNeato/aws-lambda-events. Because of GitHub limitations (https://help.github.com/articles/transferring-an-issue-to-another-repository/) this issue is being closed rather than transferred.

If it is still relevant, please open an issue in the [new repo](https://github.com/LegNeato/aws-lambda-events).

Sorry for the churn!
