### ISSUE TITLE
Add xray tracing

### ISSUE THREAD

**Issue by LegNeato** [srijs/rust-aws-lambda#17]
See https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html. There might be some non-lambda specific functionality that can be pulled out into a general crate.

See https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sendingdata.html and https://github.com/aws/aws-xray-daemon

**Comment by srijs** [comment]
As we're deprecating this project in favour of https://github.com/awslabs/aws-lambda-rust-runtime, I'm going to close this issue.
