### ISSUE TITLE
Error when running default Hello World event on Lambda

### ISSUE THREAD

**Issue by hazel-ocean** [srijs/rust-aws-lambda#19]
This might be simply because I'm building from my Macbook, but building, uploading and running the [example](https://github.com/srijs/rust-aws-lambda/blob/master/aws_lambda/examples/hello.rs) from the repo give the following error:

```
START RequestId: 03347410-8b00-11e8-b53c-4b89ac0a2d5a Version: $LATEST
fork/exec /var/task/rust-lambda-test: exec format error: PathError
null
END RequestId: 03347410-8b00-11e8-b53c-4b89ac0a2d5a
REPORT RequestId: 03347410-8b00-11e8-b53c-4b89ac0a2d5a	Duration: 12.20 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 13 MB
```

The test event I'm using is just the default event, so I would expect it to work fine.

I 100% expect this to be because of my build environment, so I'm booting up a Cloud9 environment to see if I get the same error. If not, it should be safe to include a warning in the README :).

**Comment by LegNeato** [comment]
Just to confirm, are you cross-compiling for Linux? (--target=x86_64-unknown-linux I believe). Or are you building for musl?

**Comment by srijs** [comment]
What did you specify as your handler in the lambda configuration?

My recommendation is to have the rust binary sit at the top-level of the zip archive, and the handler name needs to match the name of the binary.

**Comment by hazel-ocean** [comment]
@LegNeato Negative, Ghostrider. I did neither :)
@srijs I was doing that, but I think it's just me.

... Okay, just it working - it's definitely my build environment (macOS). I think it would be good to have a recommended way or two to build code for AWS Lambda for people like me who don't have a Linux machine handy. I'd like to hear what you guys think about that idea.

**Comment by LegNeato** [comment]
Yep, on the ol' TODO! FWIW cross building for Linux from Mac OS X with '--target' is standard in the Rust world.

**Comment by LegNeato** [comment]
You might also be interested in:

http://timryan.org/2018/07/27/cross-compiling-linux-binaries-from-macos.html
