### ISSUE TITLE
Sample Makefile

### ISSUE THREAD

**Issue by jaysonsantos** [srijs/rust-aws-lambda#21]
Hi, I was trying to make a generic way to compile and bundle the executable generated for lambda not depending on the OS you are using to develop and I came up with a Makefile that runs docker to do the build and I just wanted to share it in case you want to put it as a sample on the docs.

https://gist.github.com/jaysonsantos/c91c79ab5505ffd2063081b7c10ce9d3

**Comment by tinkyholloway** [comment]
To make it so `docker-image` is only rebuilt when `Dockerfile.lambda-builder` changes, modify the `Makefile` target adding `touch $@`:
```
docker-image: Dockerfile.lambda-builder
    docker build -t rust-amazonlinux -f Dockerfile.lambda-builder .
    touch $@
```

**Comment by tinkyholloway** [comment]
To make it so the files on the host file system have the correct permissions, add the following to the `Makefile`:
```
USERID=$(shell id -u ${USER})
GROUPID=$(shell id -g ${USER})
```
and then add the flag `-u ${USERID}:${GROUPID}` to the docker calls. This will create the build products with the calling user's user and group ID instead of that of the docker daemon's.

**Comment by tinkyholloway** [comment]
Add `strip main` to zip file target to reduce the package size:
```
main.zip: docker-image target/x86_64-unknown-linux-gnu/release/${BINARY_NAME}
    cp target/x86_64-unknown-linux-gnu/release/${BINARY_NAME} main
    strip main
    zip -D main.zip main
    rm -rf main
```

**Comment by jaysonsantos** [comment]
Hey @tinkyholloway, thanks I've updated the gist [1] with your suggestions with some changes.

[1] https://gist.github.com/jaysonsantos/c91c79ab5505ffd2063081b7c10ce9d3

**Comment by LegNeato** [comment]
I'm going to close this out for now. Please file additional issues for specific changes. Thanks for the gists and improvements!
