### ISSUE TITLE
Data to support project claims

### ISSUE THREAD

**Issue by softprops** [srijs/rust-aws-lambda#26]
A recent rust crowbar pull brought me some awareness about the state of this project and some claims about this project in comparison to rust crowbar https://github.com/ilianaw/rust-crowbar/pull/41#discussion_r216917595

I was wondering if you were willing to share the data analysis analysis that were used to support these claims

**Comment by LegNeato** [comment]
Hello! Apologies, that section was written with the Node.js runtime in mind, as it is consistently one of the slowest/most memory hungry on various public benchmarks and metrics.

I've removed the section entirely for now and filed https://github.com/srijs/rust-aws-lambda/issues/27 for writing/running our own benchmarks in the future. Thanks for raising the issue!

**Comment by softprops** [comment]
No problem and I wanted to clarify I didn't mean that to sound defensive. The internet makes that hard :) I'm actually really excited about the future rust and serverless. You are doing really great work here!

**Comment by LegNeato** [comment]
You didn't sound defensive at all! Thanks for all your work on rust-crowbar and serverless-rust, they are impressive 😃
