### ISSUE TITLE
Add support for responding to multiple event input types

### ISSUE THREAD

**Issue by LegNeato** [srijs/rust-aws-lambda#3]
Currently if you want to respond to multiple types of input you need multiple functions and/or multiple binaries. While it is fairly trivial to have one binary and manually handle different input types via things like env variables or CLI flags or multiple binaries that expose different functions, it would be nice to have something in the runtime. A benefit of this could be only one binary deployed but registered for multiple events.

I'm not sure what it would look like, but perhaps something like:

```rust
fn main() {
    lambda::Builder::new()
       .add(|input: MyType1| {
         Ok(format!("this is mytype1: {}",  input))
       })
       .add(|input: MyType2| {
         Ok(format!("this is mytype2: {}",  input))
       })
       .start()
}
```

or just passing multiple functions to `lambda::start`.

The runtime could then attempt to deserialize input (in order?) and when one succeeds, call the proper closure, otherwise try to deserialize into the next type, and so on.

**Comment by srijs** [comment]
If I had to do this today, I'd probably use serde's [`untagged`](https://serde.rs/enum-representations.html#untagged) attribute like so:

```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum Input {
    Type1(MyType1),
    Type2(MyType2)
}

fn main() {
    lambda::start(|input: Input| {
        match input {
            Input::Type1(mytype1) => {
                Ok(format!("this is mytype1: {}", mytype1))
            }
            Input::Type2(mytype2) => {
                Ok(format!("this is mytype2: {}",  mytype2))
            }
        }
    })
}
```

But I can see how a shorthand for this would be more convenient!

**Comment by LegNeato** [comment]
Oh, I wasn't aware! That actually looks super convenient already 😄. I'll close and maybe add something to the docs eventually.
