### ISSUE TITLE
Update aws_lambda_tower_web to 0.3

### ISSUE THREAD

**Issue by richardanaya** [srijs/rust-aws-lambda#30]
For some reason when I compile the hello_world example verbatim, I get an error.

https://github.com/srijs/rust-aws-lambda/blob/master/aws_lambda_tower_web/examples/hello_world.rs

Compiling pgtest v0.1.0 (file:///code)
error[E0599]: no method named `run_lambda` found for type `tower_web::ServiceBuilder<HelloWorld, tower_web::response::DefaultSerializer, tower_web::error::DefaultCatch, tower_web::middleware::Identity>` in the current scope
  --> src/main.rs:45:10
   |
45 |         .run_lambda()
   |          ^^^^^^^^^^

**Comment by richardanaya** [comment]
Hmm, maybe I have a version mismatch, it seems to work when I constrain to tower-web 0.2.1. Perhaps this is really a task to update to 0.3?

**Comment by srijs** [comment]
Yep, looks like what needs to be done here is to upgrade to tower-web 0.3.

**Comment by srijs** [comment]
Fixed in c2dc628bc0745458caa87e056029ce0534bbb611!
