### ISSUE TITLE
I'd love to help. Is there any "newcomer" issues?

### ISSUE THREAD

**Issue by golddranks** [srijs/rust-aws-lambda#32]
I've been running Rust code on Lambda myself, using a Python wrapper. I've been playing with the thought implementing the go-mimicking functionality like in this crate, but I haven't had the time and energy to do so. So I was delighted to find this crate! Is there any bit-sized tasks I could help with?

**Comment by LegNeato** [comment]
Hi! Appreciate you wanting to contribute 🎉 . We don't have any bit-sized tasks right now, but there are some medium ones like https://github.com/srijs/rust-aws-lambda/issues/8. Documentation is of course always appreciated as well!

**Comment by LegNeato** [comment]
Ah, I just wrote one! https://github.com/srijs/rust-aws-lambda/issues/34
