### ISSUE TITLE
event features are not additive

### ISSUE THREAD

**Issue by srijs** [srijs/rust-aws-lambda#36]
This is a problem I stumbled upon when building the API Gateway support crate a while ago, but never really had the chance to fully dig into and reproduce.

Essentially what happens is that cargo assumes features are additive, e.g. given the following dependency tree, cargo will enable _both_ features:

- foo
  - aws_lambda_events, features = ["string-null-none"]
- bar
  - aws_lambda_events, features = ["string-null-empty"]

The way things are implemented currently this will result in the `null-empty` feature being used everywhere, and any code in `foo` that assumes that a particular field is an `Option` will fail to compile.

If we believe this to be a problem (which I think we should), here's a couple of ideas how we could fix it:

- Be more opinionated and decide for one of the options.
- Offer the two options under different crate names.
- Offer the two options under different modules in the same crate.

Especially looking forward to your input here @LegNeato!

**Comment by LegNeato** [comment]
I've been thinking about it, and we should probably just make everything the null-none case. That feels the most idiomatic, though it's kind of a bummer for usage.

The idea of different modules sounds interesting though...it would be pretty trivial to do with the codegen. Would that be confusing? I especially like that you could pick and choose which structs have which behavior, something that wasn't possible with the feature.

I was hoping after release I'd see what most people we're using and just make that the supported option, but if this is a problem (and I would agree it is) that can't happen.
