### ISSUE TITLE
Image resize example

### ISSUE THREAD

**Issue by bernardobelchior** [srijs/rust-aws-lambda#37]
I made an example using this crate and `image` to create a 128x128 thumbnail given a bigger image. 
Should I make a PR with the code? 
You can see it [here](https://github.com/bernardobelchior/rust-aws-lambda-tutorial)

**Comment by LegNeato** [comment]
Cool!

I'm not sure we should include the code in the repo, but I think it would be great to include a link to the blog post and code somewhere in the readme or docs.

**Comment by srijs** [comment]
Nice one, glad to see the `gateway` integration is working well. Thanks for writing this up!

I second @LegNeato, and I've added a link to your blog in our readme, so folks can find it if they are on the lookout for cool examples.

Please let me know if you‘d like something changed!
