### ISSUE TITLE
Handler access to tokio handle?

### ISSUE THREAD

**Issue by ThePants999** [srijs/rust-aws-lambda#42]
Hello,

Apologies if I'm missing something, but where you said in the readme that handler functions can be async, I assumed that handler functions would be able to get access to the Tokio handle so we could spawn work onto it. Could that be added?

**Comment by srijs** [comment]
Hi!

You should be able to use [`Handle::current`](https://docs.rs/tokio/0.1.13/tokio/reactor/struct.Handle.html#method.current) inside a handler function to get access to the tokio handle.

Let me know if that helps!

**Comment by ThePants999** [comment]
I knew I'd be missing something :-D  Thanks!
